### ISSUE TITLE
META: Development of build-env:create-project command

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/terminus-build-tools-plugin#7]
The `build-env:create-project` command is under development. Backwards compatibility is not guaranteed for future changes to this command until version 1.3.0 is tagged.

Initial requirements:

- [x] Create a GitHub project from a template
  - [x] [example-drops-8-composer](https://github.com/pantheon-systems/example-drops-8-composer)
  - [x] [example-drops-7-composer](https://github.com/pantheon-systems/example-drops-7-composer)
  - [x] WordPress
- [x] Create a Pantheon site
- [x] Configure Circle CI to test the GitHub project on the Pantheon site on each PR
- [x] Has functional tests that creates GitHub/Pantheon/Circle projects and confirms that the configured Circle tests pass
- [x] Tears down test projects once tests complete
- [x] Has "plugable" `site-install` strategy when creating new sites
- [x] Detect whether site supports multidev, and degrade to dev-only testing if it does not.

Later changes:

- [x] Refactor commandfile implementation into multiple classes (requires Terminus 1.1.1)
- [ ] Repository providers other than GitHub
  - [ ] Bitbucket
  - [ ] Gitlab
- [ ] CI services other than Circle
  - [ ] Travis
  - [ ] Jenkins
  - [ ] Gitlab
- [ ] More testing improvements
  - [x] Keep last set of sites for inspection after tests; tear down old test projects at beginning of next test
  - [ ] Add flags to teardown ("obliterate") command to force deletion / ignore errors
  - [x] Add a scenario that creates a pull request on the test repository and confirms that a multidev environment is created, and that the change is tested

For discussion on permutation testing, see #5.

**Comment by ataylorme** [comment]
Cleaning up old issues. The command itself exists. If the other items need to be tracked please open a new issue for each and add to the `2.0` milestone
